apiVersion: v1
kind: ConfigMap
metadata:
  name: tidygen-backend-config
  namespace: tidygen-erp
data:
  DJANGO_ENV: "production"
  DEBUG: "False"
  ALLOWED_HOSTS: "api.tidygen.com,*.tidygen.com"
  CORS_ALLOWED_ORIGINS: "https://app.tidygen.com,https://*.tidygen.com"
  CSRF_TRUSTED_ORIGINS: "https://api.tidygen.com,https://*.tidygen.com"
  DEFAULT_FROM_EMAIL: "noreply@tidygen.com"
  FRONTEND_URL: "https://app.tidygen.com"
  WEB3_MESSAGE_PREFIX: "TidyGen ERP Login"
  REDIS_URL: "redis://tidygen-redis:6379/1"
  CELERY_BROKER_URL: "redis://tidygen-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://tidygen-redis:6379/0"
  WEB3_PROVIDER_URL: "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"
  WEB3_NETWORK_ID: "1"
